{{/*
Analysis Service Account
*/}}
{{- if .Values.analysis.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sib-k8s.analysis.fullname" . }}
  labels:
    {{- include "sib-k8s.analysis.labels" . | nindent 4 }}
{{- end }}
