{{- if .Values.auditPlugin.k8saudit.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sib-k8s.fullname" . }}-k8saudit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sib-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: k8saudit
{{- end }}
