{{- $pluginType := .Values.auditPlugin.type | default "k8saudit" }}
{{- $isWebhook := eq $pluginType "k8saudit" }}
{{- $isEks := eq $pluginType "k8saudit-eks" }}
{{- $isGke := eq $pluginType "k8saudit-gke" }}
{{- $isAks := eq $pluginType "k8saudit-aks" }}
{{- $isEnabled := or $isWebhook $isEks $isGke $isAks }}
{{- if $isEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sib-k8s.fullname" . }}-k8saudit
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sib-k8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: k8saudit
  annotations:
    {{- if $isEks }}
    {{- /* AWS EKS: IAM Roles for Service Accounts (IRSA) */}}
    {{- if and .Values.auditPlugin.k8sauditEks.useIRSA .Values.auditPlugin.k8sauditEks.iamRoleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.auditPlugin.k8sauditEks.iamRoleArn | quote }}
    {{- end }}
    {{- end }}
    {{- if $isGke }}
    {{- /* Google GKE: Workload Identity */}}
    {{- if and .Values.auditPlugin.k8sauditGke.useWorkloadIdentity .Values.auditPlugin.k8sauditGke.serviceAccountEmail }}
    iam.gke.io/gcp-service-account: {{ .Values.auditPlugin.k8sauditGke.serviceAccountEmail | quote }}
    {{- end }}
    {{- end }}
    {{- if $isAks }}
    {{- /* Azure AKS: Workload Identity */}}
    {{- if .Values.auditPlugin.k8sauditAks.useWorkloadIdentity }}
    {{- if .Values.auditPlugin.k8sauditAks.clientId }}
    azure.workload.identity/client-id: {{ .Values.auditPlugin.k8sauditAks.clientId | quote }}
    {{- end }}
    {{- if .Values.auditPlugin.k8sauditAks.tenantId }}
    azure.workload.identity/tenant-id: {{ .Values.auditPlugin.k8sauditAks.tenantId | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
